### ISSUE TITLE
Crash - Colliding entity with block

### ISSUE THREAD

**Issue by Cataratas** [noobanidus/wishingforsunshine#10]
A phantom attacked me close to the well block, and after he died the game just crashed. :/
[crash-2022-05-29_15.06.14-server.txt](https://github.com/noobanidus/wishingforsunshine/files/8793966/crash-2022-05-29_15.06.14-server.txt)

After trying to get back into my world, it crashed again.
[crash-2022-05-29_15.14.00-server.txt](https://github.com/noobanidus/wishingforsunshine/files/8793977/crash-2022-05-29_15.14.00-server.txt)

**Comment by ZestyBlaze** [comment]
Fixed in latest push, update WishingForSunshine to version 2.0.3 and you should be able to relog back into your world again
