### ISSUE TITLE
Update to fabric 1.16?

### ISSUE THREAD

**Issue by Worgrick** [noobanidus/wishingforsunshine#3]
I need a mod that allows you to control the weather in survival for my mod pack. I was hoping you can update this. I can send you the modpack if you want? I just need something, so if you can't help me maybe you could direct me somewhere eles.

**Comment by noobanidus** [comment]
I don't have any experience with Fabric, I'm sorry. I can only suggest looking for a Fabric-based discord that does mod requests; I don't know of any myself.

**Comment by Worgrick** [comment]
I appreciate you getting back to me. It's for the new extra origins mod,
and primal winter. In extra origins the florans die, the just starve to
death in the nether and end, with the primal winter mod they just starve.
It means you can't even fight the ender dragon as a floran. But they
wouldn't listen. So I was looking for a work around.
