### ISSUE TITLE
[1.16.2 Fabric] Crash when placing a well after breaking one

### ISSUE THREAD

**Issue by Samekichi** [noobanidus/wishingforsunshine#6]
The game will sometimes crash if I place a well after breaking one. 
This is really an interesting and useful mod so hope to get it fixed. By the way, a list of thrown items and their corresponding effects in Wiki or Curseforge introduction page would be great! 

(A full crash report can be found [here](https://pastebin.com/B2UQn4vq).)

**Comment by noobanidus** [comment]
It looks like it's not filtering the facing, hm.

**Comment by noobanidus** [comment]
I believe I've isolated the cause, Ill try to fix it shortly.

**Comment by noobanidus** [comment]
Hopefully all fixed! I've uploaded a new version to CurseForge and I've included default items and instructions on how the tag system works.
