### ISSUE TITLE
[1.16.5] game crashes when non-player dropped valid item touches the well

### ISSUE THREAD

**Issue by tw0jaye** [noobanidus/wishingforsunshine#9]
items dropped into a well with droppers or when an inventory containing items above the well is broken will crash the game (because it is trying to search for a player who dropped the item for the chat message but it can't find one?)

**Comment by noobanidus** [comment]
Can you please attach the crash report?

This is strange, because I have a functioning setup involving a daylight detector and some gold ingots on my 1.16.5 server.

**Comment by noobanidus** [comment]
I've not been able to replicate this and as you unfortunately haven't provided a crash report, there's nothing more I can do on the issue. Please open a new issue with the crash report if you find it repeating.
